export const CHOOSE_DATE = 'CHOOSE_DATE';
export const CHOOSE_DATE_PENDING = 'CHOOSE_DATE_PENDING';
export const CHOOSE_DATE_FULFILLED = 'CHOOSE_DATE_FULFILLED';
export const CHOOSE_DATE_REJECTED = 'CHOOSE_DATE_REJECTED';
